### ISSUE TITLE
Calling Aaru fails with System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/ipmlab#16]
Calling Aaru from ipmlab fails with:
```
Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.IOException: The handle is invalid.
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.ConsolePal.get_WindowWidth()
   at System.Console.get_WindowWidth()
   at Aaru.Progress.ClearCurrentConsoleLine()
   at Aaru.Progress.UpdateStatus(String text)
   at Aaru.Core.Devices.Dumping.Dump.Start() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/Dump.cs:line 214
   at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads, Boolean storeEncrypted, Boolean titleKeys)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
Generated Command line works without any issues when executed from Command prompt:

```
W:\aaru-5.3.1_windows_x64\aaru.exe m dump E: W:\iromlab-test\kb-a3d461b2-22f2-11ed-aa3d-0800272c26ff\ab6fb264-22f2-11ed-9c77-0800272c26ff\ab6fb264-22f2-11ed-9c77-0800272c26ff.img
```
Already tried:

- Changed [Shell value in Popen](https://github.com/KBNLresearch/ipmlab/commit/b9aa25a82a88bbd50c770455abba7173efb51150#diff-a5ec696fa37c2ca30ce2968547a56e9dde3d7c077db7d6ebf6a096d60924f74e) (no effect)

Looks like this might be the same issue:

<https://stackoverflow.com/questions/44113316/failed-to-execute-command-line-argument-from-python-script>

**Comment by bitsgalore** [comment]
After these changes Aaru runs without problems (but without any stdout/stderr capturing):

<https://github.com/KBNLresearch/ipmlab/commit/20647f316400d1695a40cc571e03f1354e77ce61>

**Comment by bitsgalore** [comment]
Some more refactoring:

<https://github.com/KBNLresearch/ipmlab/commit/aade9550ec0b7e2685012bada7a7d9ff4bf907db>

Still NO stdout/stderr capture (this reintroduces the error!). Also worth noting that read errors (bad sectors) don't influence Aaru exit status, so we have to dig into Aaru log files for that.
