### ISSUE TITLE
Aaru fails with exit code 1 if Ipmlab is run from PyPi package

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/ipmlab#23]
This happens under Linux Mint 19.3. No useful info from Aaru log/error log.

However, everything works fine when running Ipmlab from local script (launcher in Git repo). I *suspect* this has something to do with Aaru trying to write to stdout/stderr (which is shown in terminal for local script), and fact that stdout and stderr are not captured. But capturing stdout/stderr leads to the problems described here:

<https://github.com/KBNLresearch/ipmlab/issues/16>

**Comment by bitsgalore** [comment]
Update - if the packaged version of Ipmlab is launched from the terminal Aaru works as expected. So issue is definitely caused by Aaru's stdout/stderr handliing.

**Comment by bitsgalore** [comment]
Update, changed call to Aaru to this:

```Python
p = sub.Popen(args, stdout=sub.PIPE, stderr=sub.STDOUT)
for line in io.TextIOWrapper(p.stdout, encoding="utf-8"):
     logging.info(line)
```

Result (from Ipmlab log file):

```
2022-09-14 19:41:01,490 - INFO - aaru 5.3.1

2022-09-14 19:41:01,490 - INFO - Copyright © 2011-2022 Natalia Portillo

2022-09-14 19:41:01,490 - INFO - 

2022-09-14 19:41:01,772 - INFO - Output image format: Raw Disk Image.

2022-09-14 19:41:01,846 - INFO - Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

2022-09-14 19:41:01,846 - INFO -  ---> System.ArgumentOutOfRangeException: Count cannot be less than zero. (Parameter 'count')

2022-09-14 19:41:01,847 - INFO -    at System.String.Ctor(Char c, Int32 count)

2022-09-14 19:41:01,847 - INFO -    at Aaru.Progress.ClearCurrentConsoleLine()

2022-09-14 19:41:01,847 - INFO -    at Aaru.Progress.UpdateStatus(String text)

2022-09-14 19:41:01,847 - INFO -    at Aaru.Core.Devices.Dumping.Dump.Start() in /home/claunia/Development/Aaru/Aaru/Aaru.Core/Devices/Dumping/Dump.cs:line 214

2022-09-14 19:41:01,847 - INFO -    at Aaru.Commands.Media.DumpMediaCommand.Invoke(Boolean debug, Boolean verbose, String cicmXml, String devicePath, Boolean resume, String encoding, Boolean firstPregap, Boolean fixOffset, Boolean force, Boolean metadata, Boolean trim, String outputPath, String options, Boolean persistent, UInt16 retryPasses, UInt32 skip, Byte speed, Boolean stopOnError, String format, String subchannel, Boolean private, Boolean fixSubchannelPosition, Boolean retrySubchannel, Boolean fixSubchannel, Boolean fixSubchannelCrc, Boolean generateSubchannels, Boolean skipCdiReadyHole, Boolean eject, UInt32 maxBlocks, Boolean useBufferedReads, Boolean storeEncrypted, Boolean titleKeys)

2022-09-14 19:41:01,847 - INFO -    --- End of inner exception stack trace ---

2022-09-14 19:41:01,847 - INFO -    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)

2022-09-14 19:41:01,847 - INFO -    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

2022-09-14 19:41:01,847 - INFO -    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)

2022-09-14 19:41:01,847 - INFO -    at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)

2022-09-14 19:41:01,847 - INFO -    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()

2022-09-14 19:41:01,847 - INFO - --- End of stack trace from previous location where exception was thrown ---

2022-09-14 19:41:01,847 - INFO -    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()

2022-09-14 19:41:01,847 - INFO - --- End of stack trace from previous location where exception was thrown ---

2022-09-14 19:41:01,847 - INFO -    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()

2022-09-14 19:41:01,847 - INFO - --- End of stack trace from previous location where exception was thrown ---

2022-09-14 19:41:01,848 - INFO -    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()

2022-09-14 19:41:01,848 - INFO - --- End of stack trace from previous location where exception was thrown ---

2022-09-14 19:41:01,848 - INFO -    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()

2022-09-14 19:41:01,848 - INFO - --- End of stack trace from previous location where exception was thrown ---

2022-09-14 19:41:01,848 - INFO -    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()

2022-09-14 19:41:01,848 - INFO - --- End of stack trace from previous location where exception was thrown ---

2022-09-14 19:41:01,848 - INFO -    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()

2022-09-14 19:41:01,848 - INFO - --- End of stack trace from previous location where exception was thrown ---

2022-09-14 19:41:01,848 - INFO -    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()

2022-09-14 19:41:01,848 - INFO - --- End of stack trace from previous location where exception was thrown ---

2022-09-14 19:41:01,848 - INFO -    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()

2022-09-14 19:41:01,848 - INFO - --- End of stack trace from previous location where exception was thrown ---

2022-09-14 19:41:01,848 - INFO -    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()

```

**Comment by bitsgalore** [comment]
Possibly (un?)related :

<https://github.com/robotframework/robotframework/issues/4173>

**Comment by bitsgalore** [comment]
Todo: make minimal demo script that demonstrates the issue.

**Comment by bitsgalore** [comment]
Update, in Windows, Ipmlab launches Aaru in a separate console Window (which closes automatically upon completion:

![VirtualBox_Windows 10_15_09_2022_18_44_43](https://user-images.githubusercontent.com/1014449/190461319-845a6507-79d6-45e4-b81e-ef292c55c041.png)

A bit ugly, but at least it works.

**Comment by bitsgalore** [comment]
Another twist to this - in Windows, setting "shell=True" gets rid of the the terminal (in Linux this won't even run!):

```Python
 # Run Aaru as subprocess
 p = sub.run(args, shell=True)
```

**Comment by bitsgalore** [comment]
Opened Aaru issue for this:

<https://github.com/aaru-dps/Aaru/issues/749>

**Comment by bitsgalore** [comment]
Fixed now in Aaru:

<https://github.com/aaru-dps/Aaru/issues/749>
