### ISSUE TITLE
Writing of dfxml results in error on fresh install 

### ISSUE THREAD

**Issue by bitsgalore** [KBNLresearch/ipmlab#32]
Happens on fresh Linux Mint 20.1 install.

Did additional test with this script:

```python
#! /usr/bin/env python3
"""Get DFXML output using fiwalk and write it to file"""

import os
import io
from dfxml import fiwalk
import logging

def writeDfxml(imageFile, writeDirectory):
    """Generate DFXML metadata and write to file"""

    fileOut = os.path.join(writeDirectory, "dfxml.xml")

    try:
        with open(imageFile, "rb") as ifs:
            fwOutBuffer = fiwalk.fiwalk_xml_stream(imagefile=ifs)
            fwOut = fwOutBuffer.read()
    except:
        raise
        logging.error("Error extracting dfxml metadata")
        success = False

    try:
        raise
        with io.open(fileOut, "wb") as fOut:
            fOut.write(fwOut)
        success = True
    except:
        logging.error("CError writing dfxml metadata")
        success = False

    return success

def main():
    imgIn = "./test.img"
    writeDirectory = "."
    successDfxml = writeDfxml(imgIn, writeDirectory)


main()
```

Result:

```
Traceback (most recent call last):
  File "/home/johan/.local/lib/python3.8/site-packages/dfxml/fiwalk.py", line 133, in fiwalk_xml_stream
    res = Popen([fiwalk,'-V'],stdout=PIPE).communicate()[0]
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'fiwalk'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test-dfxml.py", line 40, in <module>
    main()
  File "test-dfxml.py", line 37, in main
    successDfxml = writeDfxml(imgIn, writeDirectory)
  File "test-dfxml.py", line 16, in writeDfxml
    fwOutBuffer = fiwalk.fiwalk_xml_stream(imagefile=ifs)
  File "/home/johan/.local/lib/python3.8/site-packages/dfxml/fiwalk.py", line 135, in fiwalk_xml_stream
    raise RuntimeError("Cannot execute fiwalk executable: "+fiwalk)
RuntimeError: Cannot execute fiwalk executable: fiwalk
```
Seems there's a dependency on Sleuthkit, so installed using:

```bash
sudo apt install sleuthkit
```

Updated docs as per [here](https://github.com/KBNLresearch/ipmlab/commit/6a7753a081df74aa2549154daf5ffdc575a3886a).

**Comment by bitsgalore** [comment]
Additional comment - as calling Fiwalk using the python_dfxml module can result in memory problems (see  [here](https://github.com/dfxml-working-group/dfxml_python/pull/40#discussion_r1018339154)), it might be better to exclude python_dfxml  altogether and wrap fiwalk directly in Ipmlab (this would also get rid of the somewhat clumsy installation step ).
